-- Create a table for storing payments
create table public.payments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id text not null,
  amount numeric not null,
  currency text not null,
  status text not null,
  customer_name text,
  customer_email text,
  customer_phone text,
  payment_method text default 'PayHere',
  transaction_id text,
  app_name text default 'Direct',
  meta_data jsonb
);

-- Enable Row Level Security (RLS)
alter table public.payments enable row level security;

-- Policy: Allow anyone (Anon) to INSERT records (Required if using Anon Key)
-- Ideally, use Service Role Key in backend to bypass this, but for Anon Key:
create policy "Enable insert for all users" on public.payments for insert 
with check (true);

-- Policy: Allow users to select their own records (if needed) or public read (optional)
create policy "Enable read access for all users" on public.payments for select 
using (true);
